### ISSUE TITLE
create-asset.yaml have fixed-rate and fixed-backlog in the same benchmark (?)

### ISSUE THREAD

**Issue by jorgego11** [hyperledger/caliper-benchmarks#110]
on v0.3.2    caliper-benchmarks/benchmarks/api/fabric/couchDB/contract/create-asset.yaml 

Why different rate controls in the same create-asset.yaml? 
Is this a typo?

**Comment by aklenik** [comment]
@nklincoln Any reason? Or just to demonstrate different rate control configs?

**Comment by nklincoln** [comment]
sorry for late reply - yes, this is intended. It enables 2 things:
- different configuration display
- easier compare of resource utilisation at fixed tps when using different world state stores
