### ISSUE TITLE
Manifest for hyperledger/fabric-ccenv:latest not found

### ISSUE THREAD

**Issue by yyzdtccjdtc** [hyperledger/caliper-benchmarks#121]
Docker version: 19.03.13
Docker-compose version: 1.22.0

When I run

npx caliper launch manager     --caliper-workspace .     --caliper-benchconfig benchmarks/scenario/simple/config.yaml     --caliper-networkconfig networks/fabric/v1/v1.4.0/2org1peergoleveldb/fabric-go.yaml

I got this

2020.10.06-02:53:35.401 info  [caliper] [cli-launch-manager] 	Set workspace path: /home/yyang/caliper-benchmarks
2020.10.06-02:53:35.402 info  [caliper] [cli-launch-manager] 	Set benchmark configuration path: /home/yyang/caliper-benchmarks/benchmarks/scenario/simple/config.yaml
2020.10.06-02:53:35.402 info  [caliper] [cli-launch-manager] 	Set network configuration path: /home/yyang/caliper-benchmarks/networks/fabric/v1/v1.4.0/2org1peergoleveldb/fabric-go.yaml
2020.10.06-02:53:35.402 info  [caliper] [cli-launch-manager] 	Set SUT type: fabric
2020.10.06-02:53:35.422 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2020.10.06-02:53:35.422 info  [caliper] [caliper-engine] 	Starting benchmark flow
2020.10.06-02:53:35.826 info  [caliper] [fabric-connector] 	Initializing standard connector compatible with installed SDK: 1.4.11
2020.10.06-02:53:35.932 info  [caliper] [caliper-utils] 	Executing command: cd .; export FABRIC_VERSION=1.4.0;export FABRIC_CA_VERSION=1.4.0;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml up -d;sleep 3s
Creating network "2org1peergoleveldb_default" with the default driver
Creating ca.org1.example.com    ... done
Creating orderer.example.com ... done
Creating ca.org2.example.com    ... done
Creating peer0.org2.example.com ... done
Creating peer0.org1.example.com ... done
2020.10.06-02:53:43.911 info  [caliper] [caliper-engine] 	Executed start command in 7.979 seconds
2020.10.06-02:53:43.911 info  [caliper] [connectors/v1/fabric] 	Fabric SDK version: 1.4.11; TLS: none
2020.10.06-02:53:44.385 info  [caliper] [connectors/v1/fabric] 	Org1's registrar enrolled successfully
2020.10.06-02:53:44.555 info  [caliper] [connectors/v1/fabric] 	Org2's registrar enrolled successfully
2020.10.06-02:53:44.578 info  [caliper] [connectors/v1/fabric] 	Org1's admin's materials are successfully loaded
2020.10.06-02:53:44.581 info  [caliper] [connectors/v1/fabric] 	Org2's admin's materials are successfully loaded
2020.10.06-02:53:44.584 info  [caliper] [connectors/v1/fabric] 	client0.org1.example.com's materials are successfully loaded
2020.10.06-02:53:44.586 info  [caliper] [connectors/v1/fabric] 	client0.org2.example.com's materials are successfully loaded
2020.10.06-02:53:44.586 info  [caliper] [connectors/v1/fabric] 	Channel 'mychannel' definiton being retrieved from file
2020.10.06-02:53:44.663 info  [caliper] [connectors/v1/fabric] 	Channel 'mychannel' successfully created
2020.10.06-02:53:44.663 info  [caliper] [connectors/v1/fabric] 	Sleeping 5s...
2020.10.06-02:53:49.754 info  [caliper] [connectors/v1/fabric] 	Org1's peers successfully joined mychannel: peer0.org1.example.com
2020.10.06-02:53:49.825 info  [caliper] [connectors/v1/fabric] 	Org2's peers successfully joined mychannel: peer0.org2.example.com
2020.10.06-02:53:49.826 info  [caliper] [connectors/v1/fabric] 	Sleeping 5s...
2020.10.06-02:53:54.827 info  [caliper] [caliper-engine] 	Executed "init" step in 10.916 seconds
2020.10.06-02:53:54.827 info  [caliper] [connectors/v1/fabric] 	Installing contracts for mychannel...
2020.10.06-02:53:54.857 info  [caliper] [connectors/v1/fabric] 	marbles@v0 successfully installed on Org1's peers: peer0.org1.example.com
2020.10.06-02:53:54.864 info  [caliper] [connectors/v1/fabric] 	marbles@v0 successfully installed on Org2's peers: peer0.org2.example.com
2020.10.06-02:53:54.889 info  [caliper] [connectors/v1/fabric] 	drm@v0 successfully installed on Org1's peers: peer0.org1.example.com
2020.10.06-02:53:54.897 info  [caliper] [connectors/v1/fabric] 	drm@v0 successfully installed on Org2's peers: peer0.org2.example.com
2020.10.06-02:53:54.913 info  [caliper] [connectors/v1/fabric] 	simple@v0 successfully installed on Org1's peers: peer0.org1.example.com
2020.10.06-02:53:54.920 info  [caliper] [connectors/v1/fabric] 	simple@v0 successfully installed on Org2's peers: peer0.org2.example.com
2020.10.06-02:53:54.937 info  [caliper] [connectors/v1/fabric] 	smallbank@v0 successfully installed on Org1's peers: peer0.org1.example.com
2020.10.06-02:53:54.942 info  [caliper] [connectors/v1/fabric] 	smallbank@v0 successfully installed on Org2's peers: peer0.org2.example.com
2020.10.06-02:53:54.943 info  [caliper] [connectors/v1/fabric] 	Instantiating marbles@v0 in mychannel. This might take some time...
2020.10.06-02:53:55.184 error [caliper] [caliper-engine] 	Error while performing "install" step: Error: Invalid endorsement for marbles@v0 in mychannel from peer0.org1.example.com: error starting container: error starting container: Failed to generate platform-specific docker build: Failed to pull hyperledger/fabric-ccenv:latest: API error (404): manifest for hyperledger/fabric-ccenv:latest not found: manifest unknown: manifest unknown
2020.10.06-02:53:55.185 info  [caliper] [caliper-engine] 	Executed "install" step in 0.358 seconds
2020.10.06-02:53:55.185 info  [caliper] [caliper-utils] 	Executing command: cd .; docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
The FABRIC_CA_VERSION variable is not set. Defaulting to a blank string.
The FABRIC_VERSION variable is not set. Defaulting to a blank string.
Stopping peer0.org2.example.com ... done
Stopping peer0.org1.example.com ... done
Stopping ca.org2.example.com    ... done
Stopping orderer.example.com    ... done
Stopping ca.org1.example.com    ... done
Removing peer0.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing ca.org2.example.com    ... done
Removing orderer.example.com    ... done
Removing ca.org1.example.com    ... done
Removing network 2org1peergoleveldb_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
2020.10.06-02:54:06.171 info  [caliper] [caliper-engine] 	Executed end command in 10.986 seconds
2020.10.06-02:54:06.172 error [caliper] [cli-launch-manager] 	Benchmark failed with error code 5
Usage:
 caliper launch manager --caliper-bind-sut fabric:1.4 [other options]

Options:
  --help, -h           Show usage information  [boolean]
  --version            Show version information  [boolean]
  --caliper-bind-sut   The name and version of the platform to bind to  [string]
  --caliper-bind-cwd   The working directory for performing the SDK install  [string]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [string]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [string]

Error: Benchmark failed with error code 5
    at Function.handler (/home/yyang/caliper-benchmarks/node_modules/@hyperledger/caliper-cli/lib/launch/lib/launchManager.js:70:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

I have googled it, it's said that the latest tag isn't available anymore. How can I solve this issue?

**Comment by aklenik** [comment]
The tag was removed. The workaround is to pull the matching version and tag it locally as `latest`.
```
docker pull hyperledger/fabric-ccenv:1.4.0
docker tag hyperledger/fabric-ccenv:1.4.0 hyperledger/fabric-ccenv:latest
```

Hope this helps.

**Comment by hoang-tranviet** [comment]
I am new but is there any dependency reason this core.yaml cannot be updated with hyperledger/fabric-ccenv:1.4.0?
Thanks

**Comment by aklenik** [comment]
@hoang-tranviet Can you please clarify your question? core.yaml and the cc-env image are Fabric-related artifacts. You might get better answers on a Fabric forum (mailing list, rocketchat).

**Comment by StupidBug** [comment]
@yyzdtccjdtc  If you install the chaincode through the client, you could set a customized "core.yaml" which contains image version.

> The peer image preconfigured environment variable `FABRIC_CFG_PATH` is used by the peer process to locate
the `core.yaml` configuration file at runtime. `FABRIC_CFG_PATH` is preset to the image directory `/etc/hyperledger/fabric`.
Inside this directory you'll find a default core.yaml configuration file with a SampleOrg organization (aka mspid) configured.

> You can provide your own `core.yaml` configuration file on your host, and then mount this directory inside your peer container at `/etc/hyperledger/fabric`, thereby overriding the default peer configuration. For example, your core.yaml may
set `peer.localMspId` to your own organization's mspid.
