### ISSUE TITLE
error starting container: API error (500): Could not attach to network 2org1peergoleveldb_raft_default

### ISSUE THREAD

**Issue by HelmiTrabelsi** [hyperledger/caliper-benchmarks#127]
when I start a benchmars using caliper cli 3.0 I get this error 

Error while performing "install" step: Error: Invalid endorsement for fabcar@v0 in mychannel from peer0.org1.example.com: error starting container: error starting container: API error (500): Could not attach to network 2org1peergoleveldb_raft_default: rpc error: code = NotFound desc = network 2org1peergoleveldb_raft_default not found

**Comment by aklenik** [comment]
@HelmiTrabelsi Update your docker-compose, so it'll create the default network with the expected name (keeping the underscore from the directory name). Or you can change the peer settings to attach the cc containers to the network that is actually created in your case (2org1peergoleveldbraft_default). I'd suggest the first option.
