### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by HelmiTrabelsi** [hyperledger/caliper-benchmarks#131]
I am running caliper 0.3.0 with a pre-configured fabric network 2.1 and I get this error: TypeError: Class extends value undefined is not a constructor or null

**Comment by davidkel** [comment]
@HelmiTrabelsi are you trying to use the caliper-benchmarks repo for this test ? Can you provide more detail about what exactly you tried to do and more information about the error. There isn't enough information here.

**Comment by davidkel** [comment]
No response and no real detail to go on, closing
