### ISSUE TITLE
Travis CI is no longer supported

### ISSUE THREAD

**Issue by ryjones** [hyperledger/caliper-benchmarks#134]
Travis CI has changed how open source projects are supported, and Hyperledger can no longer build there. I suggest Azure Pipelines or GitHub Actions as a replacement.

**Comment by davidkel** [comment]
We need to move this to github actions

**Comment by davidkel** [comment]
#152 could remove the network that the test currently uses, if so we would need to move this to a new test fabric

**Comment by davidkel** [comment]
added support for testing fabric chaincodes and associated benchmarks. There wasn't any builds for other platforms and given my lack of knowledge around the other connectors I will leave that as follow-on work for other contributors.
