### ISSUE TITLE
Unexpected error during benchmark execution: Error: Unable to detect required Fabric binding packages

### ISSUE THREAD

**Issue by Masuduzzaman-prince** [hyperledger/caliper-benchmarks#136]
Did anyone face this problem when trying to run caliper-benchmarks. My nodejs - version is  8.17.0
and npm - version is 6.13.4. 

![16](https://user-images.githubusercontent.com/56290550/105003663-4b3f1c00-5a76-11eb-9888-8c4cb081abbe.jpg)

**Comment by davidkel** [comment]
The plan is now to ensure that caliper-benchmarks works with newer versions of caliper as 0.3.2 is old and not supported

**Comment by davidkel** [comment]
Closing as over 1 year old and no further discussions
