### ISSUE TITLE
unable to invoke js chaincode and cannot use peer command outside the CLI

### ISSUE THREAD

**Issue by swatim2020** [hyperledger/caliper-benchmarks#140]
I am working on hyperledger fabric 2.3

Whenever I try to deploy chaincode in javascript I get the problem while invoking it and I am also not able to use peer command outside the cli.

ubuntu@ip-172-31-18-117:~/fabric-samples/test-network$ export PATH=${PWD}/../bin:$PATH

ubuntu@ip-172-31-18-117:~/fabric-samples/test-network$ export FABRIC_CFG_PATH=$PWD/../config/

ubuntu@ip-172-31-18-117:~/fabric-samples/test-network$ peer chaincode invoke -o orderer.example.com:7050 --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem -C mychannel -n mycc --peerAddresses peer0.org1.example.com:7051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt --peerAddresses peer0.org2.example.com:9051 --tlsRootCertFiles ${PWD}/organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt --isInit -c '{"function":"InitLedger","Args":[]}'

then I got the error:

**Error: 2021-03-16 13:36:52.033 UTC [main] InitCmd -> ERRO 001 Cannot run peer because cannot init crypto, specified path "/home/ubuntu/fabric-samples/config/msp" does not exist or cannot be accessed: stat /home/ubuntu/fabric-samples/config/msp: no such file or directory**

please do help

I am stuck with this for a long time

and when I try to invoke chaincode from CLI then it gives an error

Error:

**> 2021-03-16 13:34:14.062 UTC [chaincodeCmd] chaincodeInvokeOrQuery -> DEBU 05f ESCC invoke result: response:<status:500 message:"error in simulation: failed to execute transaction ab91db0d7cfd1486060dd4eda3433a795420a586a22bb9be2b840d0c4991cadc: could not launch chaincode myccv1:ef37e8fd88cd288ac9fc1cc7a03584c798a8ee7577b6aac20d6c6722009dc631: error starting container: error starting container: API error (500): Could not attach to network test: rpc error: code = NotFound desc = network test not found" > Error: endorsement failure during invoke. response: status:500 message:"error in simulation: failed to execute transaction ab91db0d7cfd1486060dd4eda3433a795420a586a22bb9be2b840d0c4991cadc: could not launch chaincode myccv1:ef37e8fd88cd288ac9fc1cc7a03584c798a8ee7577b6aac20d6c6722009dc631: error starting container: error starting container: API error (500): Could not attach to network test: rpc error: code = NotFound desc = network test not found"**

**Comment by aklenik** [comment]
This is a purely Fabric-related issue, try asking the question on Fabric forums.
