### ISSUE TITLE
Error: Invalid endorsement for marbles@v0 in mychannel from peer0.org1.example.com: 2 UNKNOWN: Stream removed

### ISSUE THREAD

**Issue by 41889732** [hyperledger/caliper-benchmarks#142]
I faced this problem when I ran npx caliper launch master --caliper-workspace . --caliper-benchconfig benchmarks/scenario/simple/config.yaml --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml. Do anyone know how to deal with it?
![image](https://user-images.githubusercontent.com/69063352/115345840-f11f3580-a1e1-11eb-9fee-180663bd61b6.png)
thx!

**Comment by hehui0316** [comment]
i face the same problems,have you solved the problem?

**Comment by 41889732** [comment]
No yet, through I can run caliper in another computer, I don't know what cause this problem.

> i face the same problems,have you solved the problem?

**Comment by hehui0316** [comment]
can you provide your environment version? such as node, npm，docker ...

**Comment by 41889732** [comment]
Docker version 19.03.6
docker-compose version 1.17.1
go version go1.14.4 linux/amd64
I can run caliper in many node version, include node 8.9.0, npm 5.5.1 and node 10.10.0, npm6.4.1

**Comment by hehui0316** [comment]
thanks, I run caliper in another computer.it works

**Comment by 41889732** [comment]
I find [signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f44685ea259] in my logs, and it can be solved by adding `- GODEBUG=netdns=go` at the environment variable for orderer and peer.
