### ISSUE TITLE
TypeError: busNetConnection.getBusinessNetwork is not a function

### ISSUE THREAD

**Issue by ramoncordeiro** [hyperledger/caliper-benchmarks#148]
I'm trying to benchmarking a Hyperledger Fabric Network developed with composer. 

When run caliper-benchmark command show the error: 'TypeError: busNetConnection.getBusinessNetwork is not a function'

I'm using node 8.17.0, caliper v0.2.0 and network is in fabric v1.1.

![erro_factory](https://user-images.githubusercontent.com/8891385/135722778-94b25e4b-687c-44f6-bf94-3f99f133db18.png)

Here my configs files. 
Benchmark-config : 
![config-bench](https://user-images.githubusercontent.com/8891385/135723043-b3530ce6-31de-49d2-aa64-32362545997a.png)
callback:
![callback](https://user-images.githubusercontent.com/8891385/135723051-05216e73-40cf-421f-981d-9bd7690ab17e.png)

**Comment by davidkel** [comment]
Unfortunately composer is end of life and caliper has not supported composer in a while so I would highly recommend that you don't try to use composer. However looking at the code I see you have 
```javascript
busNetConnection = new Map();
...
factory = busNetConnection.getBusinessNetwork().getFactory();
```
As busNetConnection is just a map object, there is no getBusinessNetwork() method which is what the error is saying, so it's a bug in your code I'm afraid

Closing
