### ISSUE TITLE
Optimize the execution of Fabric CI tests

### ISSUE THREAD

**Issue by aklenik** [hyperledger/caliper-benchmarks#169]
The following enhancements should be considered to lower the execution time of CI tests:
1. Perform CI tests only on the PR side (running again on merges doesn't seem to add extra value)
2. Parallelize CI tests based on the chaincode too, not just its language (or just based on chaincode, which would mean one CI test per benchmark/workload execution)
    1. The current script could be broken down into smaller ones (one network and channel creation, and one for each CC deployment)
    2. CI feedback would be (probably) faster and easier to interpret, failed tests would directly correspond to a chaincode or its workload
    3. Such fine-grained execution would enable additional optimization, like running tests only when their corresponding source files have changed (using, for example, this: https://github.com/marketplace/actions/file-changes-action)

**Comment by aklenik** [comment]
> It appears that it can't come from a PR request from your local repo and only worked if it was a branch on the main repo itself (needed Ry's help for that) which kind of makes it difficult for non-maintainers to contribute to this.

I don't really understand this. Isn't this an issue only for the initial creation of a workflow (since the workflow is not picked up for the intended target branch)? Or do I misunderstand the issue?

(Btw, have you seen this? https://github.com/nektos/act Looks promising if we want to "complicate" things in the workflow and test it quickly.)

**Comment by davidkel** [comment]
To summarise 
1. the builds currently only build fabric tests
2. fabric has several different sets (do we want them all ? this will be covered a bit later)
3. We should only run tests on files that have changed. If a change a benchmark file or add a benchmark file, then it should be that one that the build runs. If I change a workload module, then the associated benchmark file should be run. If I change the chaincode then we need to deploy that chaincode to ensure it is built, but then which benchmark should be run to test it ? I think there needs to be a default benchmark file that does simple tests of chaincode. I think that is the case for most of the benchmarks (they either have only a single benchmark file or there is a test benchmark file)
4. relook at the parallelisation of the runs currently they are split purely by chaincode language, but should the be split by the sample itself ?
To the question of the chaincodes supported by this repo we have for fabric
1. fixed-asset (a fabric network set of benchmarks using the contract api in go, java, node)
2. fixed-asset-base (a fabric-network set of benchmarks not using the contract api in go, node)
3. fabcar (go, java, node)
4. marbles (go, node)
5. marbles-norichquery (go, node)
6. simple (go, node)
7. smallbank (go)

fixed-asset and fixed-asset-base exist to try to benchmark a fabric network topology outside of a chaincode implementation (ie it allows you to benchmark fabric itself) which is really handy when looking for deployment bottlenecks, determining theoretical tps max and to help performance tuning the fabric code itself

The others are samples in a similar vein to fabric-samples so we could look to drop those and create new benchmark on some of the fabric samples, for example the token implementations. I see this as a separate issue to this one however but it would be optimised based on only running if a change to benchmarks is made (but we would need to rely on a nighly build to see if something changed in fabric-samples that would warrant our attention)

The other thing I would note about fabric samples is that 
1. they aren't always reliable and a lot of them aren't tested in a build
2. There has been a lot of flux within the repo recently which we don't get if we own the chaincode ourselves

**Comment by davidkel** [comment]
The implementation of this issue should also result in a demonstration of the solution working before the implementer given that it would require different types of PR to show it working
