### ISSUE TITLE
I'd like to make a performance evaluation of my Besu private network (IBFT2), rather than benchmark it.

### ISSUE THREAD

**Issue by andyafene** [hyperledger/caliper-benchmarks#184]
### Which Caliper version are you using?

v0.4.0

### Which Node.JS version are you using?

v10

### Which operating system are you using?

Ubuntu 20.04 lts

Hello,

I'd like to make a performance evaluation of my Besu private network (IBFT2), rather than benchmark it.

In other words, I'd like to measure the performance of my SUT under test, rather than making standard measurements to compare it to another system or to its previous measurements.
        
Indeed, I'd like to cover system-wide measures such as response time or latency, or measure-specific activities such as the time to write a block to persistent storage.

Is it possible to do it with Caliper?

If yes, can you tell me how to do it ? I found no information about it in the Caliper documentation.

Regard,

**Comment by davidkel** [comment]
Caliper is a load generator for blockchain networks, it can simulate different loads based on specified rate controllers and configuring those rate controllers to simulate different loads on your blockchain network. So it can evaluate the performance of your network and you can simulate different loads to evaluate how it behaves. It will capture external metrics such as TPS and latency (latency is a response time, it's the time it took to complete a transaction). For actual metrics of the blockchain itself that would require the blockchain to provide metrics itself (so you can get information such as time to write a block to persistent storage). As an example, hyperledger fabric provides metrics to either statsd or prometheus. As part of a benchmark configuration you can extract prometheus metrics which can then be consolidated into the reports that caliper generates.

I would suggest asking the Besu team on discord about whether it provides those kinds of metrics and if they can be sent to prometheus

**Comment by andyafene** [comment]
Thank you very much @davidkel !
