### ISSUE TITLE
Need help with using caliper on windows for ethereum, for now I cant find any way to install the windows dependencies and run it. 

### ISSUE THREAD

**Issue by IqraSA** [hyperledger/caliper-benchmarks#229]

**Comment by davidkel** [comment]
@IqraSA This issue is not related caliper-benchmarks, you should ask on the caliper channel of discord for help around this, or create a stackoverflow question and tag it with `hyperledger-caliper`. There you can provide details about what you have tried and what problems you encountered

**Comment by davidkel** [comment]
However as a starting point as you are on Windows I would highly recommend using WSL2 as your development environment with VSCode.

**Comment by IqraSA** [comment]
Hi Thank you so much! Daniel for the guidance. Can you also mention discord channel which i can join.

Also I'll get WSL2 as my dev env and will follow now

**Comment by davidkel** [comment]
@IqraSA You can join discord via https://discord.com/invite/hyperledger

**Comment by IqraSA** [comment]
@davidkel Hi David I have joined discord channel  (no help or guidance so far) and tried searching for ethereum tutorial everywhere. I have Linux now but still facing error in the initial caliper installation for ethereum. Can you guide anything over it. https://npm.io/package/@hyperledger/caliper-ethereum I am trying to follow this. 
![Screenshot from 2022-08-29 15-15-10](https://user-images.githubusercontent.com/13027929/187144994-4f9488fd-d297-4b90-9cb6-a0ba77947dc1.png)
