### ISSUE TITLE
Fails to run example benchmark 

### ISSUE THREAD

**Issue by victoryeo** [hyperledger/caliper-benchmarks#267]
Following steps in Readme (https://github.com/hyperledger/caliper-benchmarks/blob/main/networks/besu/1node-clique/README.md) , install and bind caliper to Besu :
Then, i run the caliper benchmark as below:
```
npx caliper launch manager --caliper-benchconfig benchmarks/scenario/ERC-20/config.yaml --caliper-networkconfig networks/besu/1node-clique/networkconfig.json --caliper-flow-skip-install --caliper-workspace .
```

Error is :
2024.07.23-11:19:48.457 info  [caliper] [caliper-worker] 	Worker #0 starting workload loop
2024.07.23-11:19:48.459 error [caliper] [connector-base] 	Unexpected error while sending request: TypeError: Cannot read properties of undefined (reading 'gas')

**Comment by victoryeo** [comment]
the command below works.
npx caliper launch manager --caliper-benchconfig benchmarks/scenario/ERC-20/config.yaml --caliper-networkconfig networks/besu/1node-clique/erc20networkconfig.json --caliper-flow-skip-install --caliper-workspace .

**Comment by davidkel** [comment]
Hi, many thanks for the PR to address the issue

**Comment by victoryeo** [comment]
Thanks, 
Can i close this issue as completed ?

**Comment by davidkel** [comment]
@victoryeo Sure you can close it.

**Comment by victoryeo** [comment]
fixed by https://github.com/hyperledger/caliper-benchmarks/pull/268
