### ISSUE TITLE
pem file not fonud

### ISSUE THREAD

**Issue by fpcfjf** [hyperledger/caliper-benchmarks#38]
Caliper benchmarks "/networks/fabric/fabric-v1.4.1/2org1peergoleveldb_raft/fabric-go-tls.yaml" need 
"
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer1.org1.example.com
    adminPrivateKey:
      path: networks/fabric/config_raft/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/key.pem

"
but fabric1.4.4  generated file does not have it, only one key "65c2644c9f91e1366a7f6185755abd6de10aecb89d6353e8352772d1c158ae42_sk", what to do

**Comment by fpcfjf** [comment]
I got it myself, mainly because of the configuration of the certificate.

**Comment by aklenik** [comment]
@fpcfjf In the samples, we renamed such HEX-based file names to `key.pem` so we don't have to change the network configuration files every time we regenerate the crypto artifacts. If you generate the artifacts with the supplied `generate.sh` script then the renaming is done automatically for you.
Of course, you can use the original file names in your tests and network config, we just do this for easier maintainability.
