### ISSUE TITLE
Too many non-option arguments: got 2, maximum of 1

### ISSUE THREAD

**Issue by dretrtg** [hyperledger/caliper-benchmarks#49]
when after this command shows Too many non-option arguments: got 2, maximum of 1

npx caliper benchmark run --caliper-workspace ./fabric_worksapce --caliper-benchconfig benchmarks/scenario/simple/config.yaml --caliper-networkconfig

**Comment by aklenik** [comment]
@dretrtg The CLI commands have been changed for v0.3.0, see the updated docs: https://hyperledger.github.io/caliper/vLatest/installing-caliper/#the-caliper-cli

Your command still works with v0.2.0, so check the installed version.

(FYI, the value for the `--caliper-networkconfig` parameter is missing from your example, I don't know whether it's just a typo or not.)
