### ISSUE TITLE
Unable to run any v1.4.1 Raft benchmarks

### ISSUE THREAD

**Issue by nimaafraz** [hyperledger/caliper-benchmarks#64]
**Trying to run a Raft benchmark with Fabric V1.4.1:**
`npx caliper launch master     --caliper-workspace .     --caliper-benchconfig benchmarks/scenario/simple/config.yaml     --caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb_raft/fabric-go-tls-solo.yaml`

**### Outcome:**
```
2020.04.23-07:26:15.413 info  [caliper] [adapters/fabric] 	Instantiating marbles@v0 in mychannel. This might take some time...
2020.04.23-07:26:40.572 error [caliper] [caliper-engine] 	Error while performing "install" step: Error: Invalid endorsement for marbles@v0 in mychannel from peer0.org1.example.com: error starting container: error starting container: API error (404): network 2org1peergoleveldb_solo_raft_default not found
2020.04.23-07:26:40.573 info  [caliper] [caliper-engine] 	Executed "install" step in 25.497 seconds
```

### **Peer log:**
```
root@ubuntu:~# docker logs -f peer0.org1.example.com
2020-04-23 07:25:52.968 UTC [nodeCmd] createChaincodeServer -> WARN 001 peer.chaincodeListenAddress is not set, using peer0.org1.example.com:7052
2020-04-23 07:25:52.971 UTC [chaincode] getLogLevelFromViper -> WARN 002 chaincode.logging.level has invalid log level WARN. defaulting to WARN
2020-04-23 07:25:52.972 UTC [chaincode] getLogLevelFromViper -> WARN 003 chaincode.logging.shim has invalid log level WARN. defaulting to WARN
2020-04-23 07:26:40.518 UTC [dockercontroller] Start -> ERRO 004 start-could not start container: API error (404): network 2org1peergoleveldb_solo_raft_default not found
2020-04-23 07:26:40.547 UTC [endorser] SimulateProposal -> ERRO 005 [mychannel][29dbeb42] failed to invoke chaincode name:"lscc" , error: API error (404): network 2org1peergoleveldb_solo_raft_default not found
error starting container
error starting container
2020-04-23 07:26:41.345 UTC [deliveryClient] try -> WARN 006 Got error: rpc error: code = Canceled desc = context canceled , at 1 attempt. Retrying in 1s
2020-04-23 07:26:41.345 UTC [blocksProvider] DeliverBlocks -> WARN 007 [mychannel] Receive error: client is closing
```

I have generated the cryptomaterial. I am also able to run the non-Raft versions of the same benchmark.

**Comment by nimaafraz** [comment]
I found the problem. There is a mismatch between the network name used in the Caliper and the compose file: `2org1peercouchdbsoloraft_default` **VS.** `2org1peercouchdb_solo_raft_default`
I had to change the network name in the following lines:

https://github.com/hyperledger/caliper-benchmarks/blob/8871b664f5a4e1b3d4927279a67f165265ae3e50/networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml#L107

https://github.com/hyperledger/caliper-benchmarks/blob/8871b664f5a4e1b3d4927279a67f165265ae3e50/networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml#L154

I'm not closing this issue as the above has to be fixed.

**Comment by nimaafraz** [comment]
I found the problem. There is a mismatch between the network name used in the Caliper and the compose file: `2org1peergoleveldb_solo_raft_default` **VS.** `2org1peergoleveldbsoloraft_default`
I had to change the network name in the following lines:

https://github.com/hyperledger/caliper-benchmarks/blob/8871b664f5a4e1b3d4927279a67f165265ae3e50/networks/fabric/docker-compose/2org1peergoleveldb_solo_raft/docker-compose-tls.yaml#L107

https://github.com/hyperledger/caliper-benchmarks/blob/8871b664f5a4e1b3d4927279a67f165265ae3e50/networks/fabric/docker-compose/2org1peergoleveldb_solo_raft/docker-compose-tls.yaml#L143

I'm not closing this issue as the above has to be fixed.

**Comment by nklincoln** [comment]
@nimaafraz - what version of docker and docker-compose are you using? There was a change in the way that the default network names were generated between versions

**Comment by nimaafraz** [comment]
> @nimaafraz - what version of docker and docker-compose are you using? There was a change in the way that the default network names were generated between versions
Hey @nklincoln,
This is my Docker version:
Docker version 19.03.8, build afacb8b7f0
-Nima

**Comment by aklenik** [comment]
@nimaafraz Try updating docker-compose (I use 1.22.0 for example). The behavior in deriving the project name from the directory name changed. The older versions discard the underscore/dash symbols, that's why you get different project names from the ones set in the YAML files.
Could you please confirm whether updating docker-compose solves your problem?

**Comment by nimaafraz** [comment]
@aklenik Just updated to docker-compose 1.25. The generated network name is still "2org1peergoleveldb_solo_raft_default".

**Comment by iceriverdog** [comment]
> I found the problem. There is a mismatch between the network name used in the Caliper and the compose file: `2org1peergoleveldb_solo_raft_default` **VS.** `2org1peergoleveldbsoloraft_default`
> I had to change the network name in the following lines:
> 
> https://github.com/hyperledger/caliper-benchmarks/blob/8871b664f5a4e1b3d4927279a67f165265ae3e50/networks/fabric/docker-compose/2org1peergoleveldb_solo_raft/docker-compose-tls.yaml#L107
> 
> https://github.com/hyperledger/caliper-benchmarks/blob/8871b664f5a4e1b3d4927279a67f165265ae3e50/networks/fabric/docker-compose/2org1peergoleveldb_solo_raft/docker-compose-tls.yaml#L143
> 
> The same also goes for the other Raft compose files:
> 
> https://github.com/hyperledger/caliper-benchmarks/blob/8871b664f5a4e1b3d4927279a67f165265ae3e50/networks/fabric/docker-compose/2org1peercouchdb_solo_raft/docker-compose-tls.yaml
> 
> https://github.com/hyperledger/caliper-benchmarks/blob/8871b664f5a4e1b3d4927279a67f165265ae3e50/networks/fabric/docker-compose/2org1peergoleveldb_raft/docker-compose-tls.yaml
> 
> **I'm not closing this issue as the above has to be fixed.**

hi，sir.  There is a mismatch between the network name used in the Caliper and the compose file. which file set the network name used in the Caliper. i just find the compose file. thank you, sir!

**Comment by aklenik** [comment]
@iceriverdog The directory that contains the docker-compose file will be used as network name: `<dirname>_default`.
So you have to make sure, that the `CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE` env vars in the docker-compose file are set to the `<dirname>_default` value. And use an up2date docker-compose version, or you will run into the problem above (see my previous comment on this issue).
