### ISSUE TITLE
panic: runtime error: index out of range with GO fixed-asset chaincode

### ISSUE THREAD

**Issue by jorgego11** [hyperledger/caliper-benchmarks#65]
I am getting error sending: chaincode stream terminated while running both range-query-pagination and rich-query-pagination. 
The chaincode-container logs shows GO errors (chaincode is GO) regarding index out of range :   **"panic: runtime error: index out of range"**
This would probably crash the chaincode which could explain the  the peer logs show    failed to invoke chaincode name:"fixed-asset" , error: chaincode stream terminated.
This problem is independent of the load.  It always happen with the GO fixed-asset chaincode.

**Comment by nklincoln** [comment]
The only item common to those is the `getAllResults` function, within which line 197 might be the culprit:

`results = append(results, &fixedAsset)` might be a solution there

**Comment by nklincoln** [comment]
closed by merge of #72
