### ISSUE TITLE
[NetworkConfig101.js]: NetworkConfig101 - problem reading the PEM file 

### ISSUE THREAD

**Issue by Luciferjason** [hyperledger/caliper-benchmarks#66]
I am installing hyperledger caliber using the local NPM found at https://hyperledger.github.io/caliper/v0.3/installing-caliper/. Once I invoke the local CLI binary (step 4) using the command,
 npx caliper launch master
--caliper-workspace .
--caliper-benchconfig benchmarks/scenario/simple/config.yaml
--caliper-networkconfig networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go.yaml

I got the following log error:
2020.04.24-15:24:19.250 info  [caliper] [cli-launch-master] 	Set workspace path: /root/go/src/github.com/hyperledger/caliper/caliper-benchmarks
2020.04.24-15:24:19.253 info  [caliper] [cli-launch-master] 	Set benchmark configuration path: /root/go/src/github.com/hyperledger/caliper/caliper-benchmarks/benchmarks/scenario/simple/config.yaml
2020.04.24-15:24:19.253 info  [caliper] [cli-launch-master] 	Set network configuration path: /root/go/src/github.com/hyperledger/caliper/caliper-benchmarks/networks/fabric/fabric-v1.4.1/2org1peergoleveldb/fabric-go-tls.yaml
2020.04.24-15:24:19.253 info  [caliper] [cli-launch-master] 	Set SUT type: fabric
2020.04.24-15:24:19.270 info  [caliper] [benchmark-validator] 	No observer specified, will default to `none`
2020.04.24-15:24:19.276 info  [caliper] [caliper-engine] 	Starting benchmark flow
2020.04.24-15:24:20.562 info  [caliper] [adapters/fabric] 	Initializing standard adaptor compatible with installed SDK: 1.4.8
2020.04.24-15:24:20.981 info  [caliper] [caliper-utils] 	Executing command: cd caliper-benchmarks; export FABRIC_VERSION=1.4.1;export FABRIC_CA_VERSION=1.4.1;docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose-tls.yaml up -d;sleep 3s
Creating network "2org1peergoleveldb_default" with the default driver
Creating ca.org1.example.com    ... done
Creating orderer.example.com ... done
Creating ca.org2.example.com ... done
Creating peer0.org1.example.com ... done
Creating peer0.org2.example.com ... done
2020.04.24-15:24:31.463 info  [caliper] [caliper-engine] 	Executed start command in 10.483 seconds
2020.04.24-15:24:31.464 info  [caliper] [adapters/fabric] 	Fabric SDK version: 1.4.8; TLS: server
2020-04-24T07:24:31.492Z - error: [NetworkConfig101.js]: NetworkConfig101 - problem reading the PEM file :: Error: ENOENT: no such file or directory, open '/root/go/src/github.com/hyperledger/caliper/caliper-benchmarks/networks/fabric/config_solo/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem'
2020.04.24-15:24:31.494 error [caliper] [caliper-engine] 	Error while performing "init" step: Error: ENOENT: no such file or directory, open '/root/go/src/github.com/hyperledger/caliper/caliper-benchmarks/networks/fabric/config_solo/crypto-config/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem'
2020.04.24-15:24:31.495 info  [caliper] [caliper-engine] 	Executed "init" step in 0.031 seconds
2020.04.24-15:24:31.495 info  [caliper] [caliper-utils] 	Executing command: cd caliper-benchmarks; docker-compose -f networks/fabric/docker-compose/2org1peergoleveldb/docker-compose-tls.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*
The FABRIC_CA_VERSION variable is not set. Defaulting to a blank string.
The FABRIC_VERSION variable is not set. Defaulting to a blank string.
Removing peer0.org2.example.com ... done
Removing peer0.org1.example.com ... done
Removing ca.org1.example.com    ... done
Removing ca.org2.example.com    ... done
Removing orderer.example.com    ... done
Removing network 2org1peergoleveldb_default
"docker rm" requires at least 1 argument.
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
2020.04.24-15:24:33.217 info  [caliper] [caliper-engine] 	Executed end command in 1.721 seconds
2020.04.24-15:24:33.217 error [caliper] [cli-launch-master] 	Benchmark failed with error code 4
Usage:
 caliper launch master --caliper-bind-sut fabric:1.4.1 [other options]

Options:
  --help, -h           Show usage information  [布尔]
  --version            Show version information  [布尔]
  --caliper-bind-sut   The name and version of the platform to bind to  [字符串]
  --caliper-bind-cwd   The working directory for performing the SDK install  [字符串]
  --caliper-bind-args  Additional arguments to pass to "npm install". Use the "=" notation when setting this parameter  [字符串]
  --caliper-bind-file  Yaml file to override default (supported) package versions when binding an SDK  [字符串]

Error: Benchmark failed with error code 4
    at Function.handler (/root/go/src/github.com/hyperledger/caliper/packages/caliper-cli/lib/launch/lib/launchMaster.js:70:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by aklenik** [comment]
@Luciferjason As the error states, your crypto files are not found, probably because you haven't generated them after cloning the repo: https://github.com/hyperledger/caliper-benchmarks#running-a-benchmark

**Comment by MUKESHBADIGINENI** [comment]
> @Luciferjason As the error states, your crypto files are not found, probably because you haven't generated them after cloning the repo: https://github.com/hyperledger/caliper-benchmarks#running-a-benchmark

I tried this, but it's popping up command not found
![image](https://user-images.githubusercontent.com/37984445/111783136-db71d400-88f4-11eb-979e-fde65dabdb7a.png)

**Comment by Dynnforever** [comment]
Hi, I have run all ./generate.sh file under config_x. However, the error still there.

**Comment by puneetsingh166** [comment]
run using sudo bash generate.sh
