### ISSUE TITLE
Ethereum 1node network config not working

### ISSUE THREAD

**Issue by kiview** [hyperledger/caliper-benchmarks#68]
When building the [Docker image](https://github.com/hyperledger/caliper-benchmarks/blob/master/networks/ethereum/1node/Dockerfile), the docker build process will fail because of a wrong genesis configuration:

```
Fatal: Failed to write genesis block: unsupported fork ordering: petersburgBlock not enabled, but istanbulBlock enabled at 0
```

When changing the genesis configuration to this, building proceeds, however we get an error ` err="invalid block 18: unknown ancestor"`:
```json
{
  "config": {
    "chainId": 21194,
    "istanbulBlock": 0,
    "petersburgBlock": 0,
    "constantinopleBlock": 0,
    "byzantiumBlock": 0,
    "eip158Block": 0,
    "eip155Block": 0,
    "eip150Block": 0,
    "homesteadBlock": 0,
    "ethash": {}
  },
  "nonce": "0x0",
  "timestamp": "0x5cd09c57",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x2faf080",
  "difficulty": "0x80000",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "c0a8e4d217eb85b812aeb1226fab6f588943c2c2": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```

Building the image suceeds instead of above mentioned error when using this config,

**Comment by aklenik** [comment]
@kiview Thanks for raising the issue 👍 Would you like to submit a PR with the fix?

**Comment by kiview** [comment]
@aklenik For sure. I will just double check if the values like this really make sense and then provide PR :slightly_smiling_face:

**Comment by kiview** [comment]
From the Geth source code, we can actually infer, that all previous forks need to be specified:
https://github.com/ethereum/go-ethereum/blob/master/params/config.go#L435
