### ISSUE TITLE
all .pem files are missing

### ISSUE THREAD

**Issue by alessandrovalori90** [hyperledger/caliper-benchmarks#69]
all "crypto-config" folders have been deleted from commit: e6e2eaea0b37dc4f82d45feec8d6053358eb34fe on Apr 16, 2020. To make work the examples had to go pick from old commits.

**Comment by aklenik** [comment]
@alessandrovalori90 That is intentional, as they are generated artifacts. Follow the readme instructions to regenerate them after cloning the repo: https://github.com/hyperledger/caliper-benchmarks#running-a-benchmark
